export const NotificationEvent = {
   BOOKING: "BOOKING",
   ACTIVITY: "ACTIVITY",
   REGISTER: "REGISTER",
   NEWBADGE: "NEWBADGE",
};

export const NotificationAction = {
   CREATE: "CREATE",
   REQUEST: "REQUEST",
   UPDATE: "UPDATE",
   APPROVE: "APPROVE",
   APPROVEBYADMIN: "APPROVEBYADMIN",
   APPROVEUPDATEADMIN: "APPROVEUPDATEADMIN", //THIS IS TO UPDATE ADMIN
   REJECT: "REJECT",
   REJECTBYADMIN: "REJECTBYADMIN",
   REJECTUPDATEADMIN: "REJECTUPDATEADMIN", //THIS IS PURELY TO UPDATE ADMIN
   CANCEL: "CANCEL",
   CANCELBYADMIN: "CANCELBYADMIN",
   CANCELUPDATEADMIN: "CANCELUPDATEADMIN",
   DISABLED: "DISABLED",
   DELETE: "DELETE",
};
